[package]
name = "calculator"
version = "0.1.0"
authors = ["Xargin <cao1988228@163.com>"]
edition = "2018"


[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
lalrpop-util = "0.17.1"
regex = "0.2.1"
