[package]
name = "bool_parser"
version = "0.1.0"
authors = ["Xargin <buaa.cch@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
