# 注意
# EXPR         ← ATOM ((AND/OR) ATOM)*
# 这样是不行的
# EXPR         ← ATOM (AND/OR ATOM)*

EXPR         ← ATOM (BINOP ATOM)*
ATOM         ← (COMP) / '(' EXPR ')'
COMP        ← FIELD OP VALUE
BINOP       ← AND / OR
FIELD       ←  < [a-z]+ >
AND         ← < 'and' >
OR         ← < 'or' >
OP           ← EQ / NEQ / GT
EQ           ← <'='>
NEQ          ← <'!='>
GT           ← <'>'>
VALUE        ←  STRING_LIT / NUM_LIT
NUM_LIT      ←  < [0-9]+ >
STRING_LIT   ←  < [a-zA-Z]+ >
%whitespace  ←  [ \t\r\n]*


